### PR TITLE
Change the formatting to make the doc clearer.

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by tridium** [comment]
The `logLevel` option basically lets you set the verbosity of the output. If you set it to `SEVERE` then only `SEVERE` errors will be logged; `WARNING` means you will get `SEVERE` and `WARNING` and so on. Right now, `WARNING` and `SEVERE` will be sent to `err()` and `INFO` and lower will be sent to `log()`.

But I wonder if the way you have it in the docs, where you get the string msg and the log level as two different arguments, would be simpler. So you'd only get one log function instead of two, and you'd just handle the output as you wish depending on the log level you got, something like this:

```
log: function (msg, level) {
  switch(level) {
    case 'SEVERE':
    case 'WARNING':
      return console.error(msg);
    default:
      return console.log(msg);
  }
}
```

What do you think?

Thanks -

Logan

**Comment by theofidry** [comment]
Agreed it would be easier to deal with. I would just keep the level as optional.

**Comment by tridium** [comment]
Updated and merged. Thanks for making this change!

Logan

**Comment by theofidry** [comment]
You're welcome, glad to do the first PR!

**Pull request merged**
